export const adminRoleConfig = {
  hasChecklist: true,
  isWelcomeEligible: true,
  content: {
    title: 'Welcome to the admin workspace',
    subtitle: 'Your guided path covers monitoring, account setup, records, submissions, reports, and onboarding adoption.',
    bullets: [
      'Monitor the portal - start with overview counts, notifications, and submission movement.',
      'Keep access organized - manage users, roles, schools, programs, and deadlines from one workspace.',
      'Support adoption - use onboarding analytics and practice mode to help users learn safely.',
    ],
  },
  tasks: [
    {
      id: 'admin-overview',
      label: 'Explore the admin dashboard',
      description: 'Open the Admin Overview to check system health and navigation.',
      route: '/admin',
      completeOn: ['admin.overview_visited'],
      tourChapterId: 'admin-dashboard',
    },
    {
      id: 'admin-users',
      label: 'View the user list',
      description: 'Visit Users to review accounts, pending roles, and onboarding adoption.',
      route: '/admin/users',
      completeOn: ['admin.users_visited'],
      tourChapterId: 'admin-users',
    },
    {
      id: 'admin-resources',
      label: 'View schools or programs',
      description: 'Open Schools or Programs to review the records that power workflows.',
      route: '/admin/schools',
      routes: ['/admin/schools', '/admin/programs'],
      completeOn: ['admin.resources_visited'],
      tourChapterId: 'admin-resources',
    },
    {
      id: 'admin-submissions',
      label: 'View submissions',
      description: 'Visit Submissions to monitor AIP and PIR status division-wide.',
      route: '/admin/submissions',
      completeOn: ['admin.submissions_visited'],
      tourChapterId: 'admin-submissions',
    },
    {
      id: 'admin-reports-settings',
      label: 'Review reports or settings',
      description: 'Open Reports, Settings, or Consolidation to review exports and configuration.',
      route: '/admin/reports',
      routes: ['/admin/reports', '/admin/settings', '/admin/consolidation-template'],
      completeOn: ['admin.reports_settings_visited'],
      tourChapterId: 'admin-reports-settings',
    },
  ],
  hints: [],
  practiceTasks: [
    {
      id: 'practice-admin-create-user',
      label: 'Practice: Create a user',
      description: 'Fill out the user creation form on a mock account - nothing is saved.',
      practiceType: 'admin_create_user',
      completeOn: ['practice.admin_user_created'],
    },
    {
      id: 'practice-admin-assign-role',
      label: 'Practice: Assign a role',
      description: 'Change the role of a mock user - no real accounts are modified.',
      practiceType: 'admin_assign_role',
      completeOn: ['practice.admin_role_assigned'],
    },
  ],
};
