export const cesRoleConfig = {
  hasChecklist: true,
  isWelcomeEligible: true,
  content: {
    title: 'Welcome to your CES workspace',
    subtitle: 'Your guide covers queue review, decision controls, and your own AIP/PIR submissions.',
    bullets: [
      'Focus the queue - filter pending AIPs and PIRs before opening a document.',
      'Review with context - read the content first, then approve, note, forward, or return.',
      'Keep your own reports moving - use the same guided AIP and PIR workspaces for CES-owned programs.',
    ],
  },
  tasks: [
    {
      id: 'ces-queue',
      label: 'View the review queue',
      description: 'Open the CES queue and learn how pending documents are organized.',
      route: '/ces',
      completeOn: ['ces.queue_visited'],
      tourChapterId: 'ces-dashboard',
    },
    {
      id: 'ces-filter',
      label: 'Filter submissions',
      description: 'Use search, period, or document tabs to narrow the queue.',
      route: '/ces',
      completeOn: ['ces.filter_applied'],
      tourChapterId: 'ces-dashboard',
      tourStepIds: ['filters'],
    },
    {
      id: 'ces-open-review',
      label: 'Open a submission for review',
      description: 'Open one AIP or PIR from the queue to inspect the document.',
      route: '/ces',
      routePrefix: '/ces/',
      completeOn: ['ces.review_opened'],
      tourChapterId: 'ces-dashboard',
      tourStepIds: ['queue'],
    },
    {
      id: 'ces-actions',
      label: 'Find the action controls',
      description: 'Find the review content and action controls inside a submission.',
      route: '/ces',
      routePrefix: '/ces/',
      completeOn: ['ces.action_area_viewed'],
      tourChapterId: 'ces-review',
    },
    {
      id: 'ces-aip-form',
      label: 'Open your AIP form',
      description: 'Navigate to the AIP form for one of your assigned programs.',
      route: '/aip',
      completeOn: ['ces.aip_form_visited'],
      tourChapterId: 'aip',
      tourStepIds: ['program-selector', 'step-nav'],
    },
    {
      id: 'ces-program',
      label: 'Select an assigned program',
      description: 'Choose one of your assigned programs to load the AIP editor.',
      route: '/aip',
      completeOn: ['author.program_selected'],
      tourChapterId: 'aip',
      tourStepIds: ['program-selector'],
    },
    {
      id: 'ces-file-pir',
      label: 'File a quarterly PIR',
      description: 'Open the PIR workspace to report activities against your AIP.',
      route: '/pir',
      completeOn: ['ces.pir_form_visited'],
      tourChapterId: 'pir',
      tourStepIds: ['program-selector', 'step-nav'],
    },
  ],
  hints: [
    {
      id: 'ces-filters',
      pathname: '/ces',
      target: 'ces-filters',
      title: 'Start with the queue filters',
      description: 'A quick search or period filter is the fastest way to narrow live submissions before opening one.',
      pendingTaskId: 'ces-filter',
    },
    {
      id: 'ces-aip-autosave',
      pathname: '/aip',
      target: 'form-autosave',
      title: 'Draft saving is already on',
      description: 'Once you start editing, autosave keeps your work safe across sessions.',
      requiredTaskId: 'ces-aip-form',
      pendingTaskId: 'ces-program',
    },
  ],
  practiceTasks: [
    {
      id: 'practice-ces-forward',
      label: 'Practice: Forward a PIR to Admin',
      description: 'Note and forward a mock PIR to Admin - no real records change.',
      practiceType: 'ces_forward',
      completeOn: ['practice.ces_forwarded'],
    },
    {
      id: 'practice-ces-return',
      label: 'Practice: Return a PIR',
      description: 'Return a mock PIR with feedback - no real records change.',
      practiceType: 'ces_return',
      completeOn: ['practice.ces_returned'],
    },
    {
      id: 'practice-ces-submit-aip',
      label: 'Practice: Submit an AIP',
      description: 'Walk through the AIP submission flow on a mock program - no real data is affected.',
      practiceType: 'aip_submit',
      completeOn: ['practice.aip_submitted'],
    },
    {
      id: 'practice-ces-file-pir',
      label: 'Practice: File a PIR',
      description: 'Try the quarterly PIR filing flow without submitting anything real.',
      practiceType: 'pir_submit',
      completeOn: ['practice.pir_submitted'],
    },
  ],
};
