export const cesRoleConfig = {
  hasChecklist: true,
  isWelcomeEligible: true,
  content: {
    title: 'Welcome to your CES workspace',
    subtitle: 'Review PIR submissions from your division — and file your own AIP and PIR reports.',
    bullets: [
      'Review PIRs — quarterly reports from division personnel and cluster coordinators arrive here for your action.',
      'Submit your own AIP — plan your programs and activities through the structured AIP form.',
      'File quarterly PIRs — report your actual activities and spending against your planned targets each quarter.',
    ],
  },
  tasks: [
    {
      id: 'ces-queue',
      label: 'View the review queue',
      description: 'Open the CES queue and review the forwarded PIR list.',
      route: '/ces',
      completeOn: ['ces.queue_visited'],
      tourSteps: [
        {
          target: 'ces-filters',
          title: 'Queue Filters',
          description: 'Use these to narrow the queue by school name or quarter. At quarter-end, filtering first is the fastest way to find submissions that need immediate action.',
          placement: 'bottom',
        },
        {
          target: 'ces-queue',
          title: 'Submissions Table',
          description: 'Every PIR forwarded to your level appears in this table. Click any row to open that school\'s report and begin your review.',
          placement: 'top',
        },
      ],
    },
    {
      id: 'ces-filter',
      label: 'Filter submissions',
      description: 'Use the filters to narrow the queue by school or quarter.',
      route: '/ces',
      completeOn: ['ces.filter_applied'],
      tourSteps: [
        {
          target: 'ces-filters',
          title: 'Filter Bar',
          description: 'Type a school name or select a quarter here. The table updates instantly — no need to press Enter. Use this before opening any submission to focus on what matters first.',
          placement: 'bottom',
        },
      ],
    },
    {
      id: 'ces-open-review',
      label: 'Open a submission for review',
      description: 'Open one PIR from the queue to inspect the report.',
      route: '/ces',
      completeOn: ['ces.review_opened'],
      tourSteps: [
        {
          target: 'ces-queue',
          title: 'Opening a PIR',
          description: 'Click any row in this table to open that school\'s report. You will see their reported activities, expenditures for the quarter, and any attachments they uploaded.',
          placement: 'top',
        },
      ],
    },
    {
      id: 'ces-actions',
      label: 'Find the action controls',
      description: 'Find the Note & Forward and Return controls in a review.',
      route: '/ces',
      completeOn: ['ces.action_area_viewed'],
      tourSteps: [
        {
          target: 'ces-review-content',
          title: 'Report Content',
          description: 'This section shows what the school reported — activities completed and money spent. Read through this before deciding what action to take.',
          placement: 'bottom',
          missingTargetHint: 'Open a PIR from the queue first — the review content and action buttons appear inside each submission.',
        },
        {
          target: 'ces-review-actions',
          title: 'Action Buttons',
          description: '"Note & Forward" sends the PIR up to the next level. "Return" sends it back with your feedback. Always write a clear note when returning so the school knows what to fix.',
          placement: 'bottom',
          missingTargetHint: 'Open a PIR from the queue first — the action buttons appear at the top of each submission.',
        },
      ],
    },
    {
      id: 'ces-aip-form',
      label: 'Open your AIP form',
      description: 'Navigate to the AIP form and load it for one of your assigned programs.',
      route: '/aip',
      completeOn: ['ces.aip_form_visited'],
      tourSteps: [
        {
          target: 'form-step-nav',
          title: 'AIP Form Steps',
          description: 'The AIP is divided into sections — work through each one in order before reaching the final review and submission step.',
          placement: 'bottom',
          prerequisiteTarget: 'aip-form-active',
          missingTargetHint: 'Open the AIP form first by clicking "My AIP" in the top navigation.',
        },
        {
          target: 'form-program-selector',
          title: 'Program Selector',
          description: 'Select one of your assigned programs here to start. Each program has its own separate budget and activity entries.',
          placement: 'bottom',
        },
      ],
    },
    {
      id: 'ces-program',
      label: 'Select an assigned program',
      description: 'Choose one of your assigned programs to load the AIP form.',
      route: '/aip',
      completeOn: ['author.program_selected'],
      tourSteps: [
        {
          target: 'form-program-selector',
          title: 'Choose a Program',
          description: 'Pick one of your assigned programs from this list. Once selected, the form loads that program\'s activities and budget fields.',
          placement: 'bottom',
          missingTargetHint: 'Open the AIP form first by clicking "My AIP" in the top navigation.',
        },
      ],
    },
    {
      id: 'ces-file-pir',
      label: 'File a quarterly PIR',
      description: 'Open the PIR form to report your quarterly activities against your AIP.',
      route: '/pir',
      completeOn: ['ces.pir_form_visited'],
      tourSteps: [
        {
          target: 'form-step-nav',
          title: 'PIR Form Steps',
          description: 'The PIR walks you through reporting actual activities, expenditures, and outcomes for the quarter — matched against what you planned in your AIP.',
          placement: 'bottom',
          prerequisiteTarget: 'pir-form-active',
          missingTargetHint: 'Open the PIR form first by clicking "My PIR" in the top navigation.',
        },
      ],
    },
  ],
  hints: [
    {
      id: 'ces-filters',
      pathname: '/ces',
      target: 'ces-filters',
      title: 'Start with the queue filters',
      description: 'A quick search or quarter filter is the fastest way to narrow live submissions before opening one.',
      pendingTaskId: 'ces-filter',
    },
    {
      id: 'ces-aip-autosave',
      pathname: '/aip',
      target: 'form-autosave',
      title: 'Draft saving is already on',
      description: 'Once you start editing, autosave keeps your work safe across sessions.',
      requiredTaskId: 'ces-aip-form',
      pendingTaskId: 'ces-program',
    },
  ],
  practiceTasks: [
    {
      id: 'practice-ces-forward',
      label: 'Practice: Forward a PIR to Admin',
      description: 'Note and forward a mock PIR to Admin — no real records change.',
      practiceType: 'ces_forward',
      completeOn: ['practice.ces_forwarded'],
    },
    {
      id: 'practice-ces-return',
      label: 'Practice: Return a PIR',
      description: 'Return a mock PIR with feedback — no real records change.',
      practiceType: 'ces_return',
      completeOn: ['practice.ces_returned'],
    },
    {
      id: 'practice-ces-submit-aip',
      label: 'Practice: Submit an AIP',
      description: 'Walk through the AIP submission flow on a mock program — no real data is affected.',
      practiceType: 'aip_submit',
      completeOn: ['practice.aip_submitted'],
    },
    {
      id: 'practice-ces-file-pir',
      label: 'Practice: File a PIR',
      description: 'Try the quarterly PIR filing flow without submitting anything real.',
      practiceType: 'pir_submit',
      completeOn: ['practice.pir_submitted'],
    },
  ],
};
