export const divisionRoleConfig = {
  hasChecklist: true,
  isWelcomeEligible: true,
  content: {
    title: 'Welcome to your planning and review workspace',
    subtitle: 'Your guide covers your own AIP/PIR work plus focal-person recommendation tasks.',
    bullets: [
      'Start from the dashboard - see planning, reporting, and submission history in one place.',
      'Submit clean documents - use autosave, section navigation, and final review before sending.',
      'Recommend responsibly - review assigned school documents, then recommend or return with clear remarks.',
    ],
  },
  tasks: [
    {
      id: 'division-dashboard',
      label: 'View your dashboard',
      description: 'Open your dashboard and learn where AIP, PIR, and history areas live.',
      route: '/',
      completeOn: ['author.dashboard_visited'],
      tourChapterId: 'user-dashboard',
    },
    {
      id: 'division-open-form',
      label: 'Open an AIP form',
      description: 'Open the AIP workspace for one of your assigned programs.',
      route: '/aip',
      completeOn: ['author.aip_form_visited'],
      tourChapterId: 'aip',
      tourStepIds: ['program-selector', 'step-nav'],
    },
    {
      id: 'division-program',
      label: 'Select an assigned program',
      description: 'Choose a program so the AIP editor can load its activities and budget.',
      route: '/aip',
      completeOn: ['author.program_selected'],
      tourChapterId: 'aip',
      tourStepIds: ['program-selector'],
    },
    {
      id: 'division-save',
      label: 'Save a draft section',
      description: 'Enter a first draft section and confirm autosave is protecting your work.',
      route: '/aip',
      completeOn: ['author.draft_saved'],
      tourChapterId: 'aip',
      tourStepIds: ['autosave'],
    },
    {
      id: 'division-review',
      label: 'Reach the AIP review step',
      description: 'Complete the form sections and open the final review area.',
      route: '/aip',
      completeOn: ['author.review_area_opened'],
      tourChapterId: 'aip',
      tourStepIds: ['review-submit'],
    },
    {
      id: 'division-open-pir',
      label: 'Open a PIR form',
      description: 'Open the quarterly report workspace for one of your assigned programs.',
      route: '/pir',
      completeOn: ['author.pir_form_visited'],
      tourChapterId: 'pir',
      tourStepIds: ['program-selector'],
    },
    {
      id: 'division-pir-program',
      label: 'Select a PIR program',
      description: 'Choose an assigned program for the current reporting period.',
      route: '/pir',
      completeOn: ['author.pir_program_selected'],
      tourChapterId: 'pir',
      tourStepIds: ['program-selector', 'step-nav'],
    },
    {
      id: 'division-pir-review',
      label: 'Reach the PIR review step',
      description: 'Complete the PIR sections and open the final review area.',
      route: '/pir',
      completeOn: ['author.pir_review_area_opened'],
      tourChapterId: 'pir',
      tourStepIds: ['review-submit'],
    },
    {
      id: 'division-focal-queue',
      label: 'Open the focal review queue',
      description: 'Visit the recommendation queue for school AIPs and PIRs assigned to you.',
      route: '/division',
      completeOn: ['division.focal_queue_visited'],
      tourChapterId: 'division-focal-queue',
    },
    {
      id: 'division-focal-review',
      label: 'Find recommendation controls',
      description: 'Open a queued document and locate the recommend and return actions.',
      route: '/division',
      routePrefix: '/division/',
      completeOn: ['division.focal_action_area_viewed'],
      tourChapterId: 'division-focal-review',
    },
  ],
  hints: [
    {
      id: 'division-autosave',
      pathname: '/aip',
      target: 'form-autosave',
      title: 'Draft saving is already on',
      description: 'Once you start editing, autosave keeps your first draft section from getting lost.',
      requiredTaskId: 'division-open-form',
      pendingTaskId: 'division-save',
    },
  ],
  practiceTasks: [
    {
      id: 'practice-division-submit-aip',
      label: 'Practice: Submit an AIP',
      description: 'Walk through the AIP submission step on a mock program - no real data is affected.',
      practiceType: 'aip_submit',
      completeOn: ['practice.aip_submitted'],
    },
    {
      id: 'practice-division-file-pir',
      label: 'Practice: File a PIR',
      description: 'Try the quarterly PIR filing flow without submitting anything real.',
      practiceType: 'pir_submit',
      completeOn: ['practice.pir_submitted'],
    },
  ],
};
