export const schoolRoleConfig = {
  hasChecklist: true,
  isWelcomeEligible: true,
  content: {
    title: 'Welcome to the AIP-PIR Portal',
    subtitle: 'Your guided path starts with the dashboard, then moves through planning, reporting, and a safe practice run.',
    bullets: [
      'Find your next action - the dashboard shows what needs attention first.',
      'Plan with confidence - select a program, draft the AIP, and review before submitting.',
      'Report quarterly - file PIRs from the approved plan and track every status change.',
    ],
  },
  tasks: [
    {
      id: 'school-dashboard',
      label: 'View your dashboard',
      description: 'Open your dashboard and learn where the AIP, PIR, and history areas live.',
      route: '/',
      completeOn: ['author.dashboard_visited'],
      tourChapterId: 'user-dashboard',
    },
    {
      id: 'school-open-form',
      label: 'Open an AIP form',
      description: 'Open the AIP workspace and learn how the form is organized.',
      route: '/aip',
      completeOn: ['author.aip_form_visited'],
      tourChapterId: 'aip',
      tourStepIds: ['program-selector', 'step-nav'],
    },
    {
      id: 'school-program',
      label: 'Select your first program',
      description: 'Choose a program so the AIP editor can load its activities and budget.',
      route: '/aip',
      completeOn: ['author.program_selected'],
      tourChapterId: 'aip',
      tourStepIds: ['program-selector'],
    },
    {
      id: 'school-save',
      label: 'Save a draft section',
      description: 'Enter a first draft section and confirm autosave is protecting your work.',
      route: '/aip',
      completeOn: ['author.draft_saved'],
      tourChapterId: 'aip',
      tourStepIds: ['autosave'],
    },
    {
      id: 'school-review',
      label: 'Reach the AIP review step',
      description: 'Complete the form sections and open the final review area.',
      route: '/aip',
      completeOn: ['author.review_area_opened'],
      tourChapterId: 'aip',
      tourStepIds: ['review-submit'],
    },
    {
      id: 'school-open-pir',
      label: 'Open a PIR form',
      description: 'Open the quarterly report workspace tied to your submitted AIP.',
      route: '/pir',
      completeOn: ['author.pir_form_visited'],
      tourChapterId: 'pir',
      tourStepIds: ['program-selector'],
    },
    {
      id: 'school-pir-program',
      label: 'Select a PIR program',
      description: 'Choose the program for the current reporting period.',
      route: '/pir',
      completeOn: ['author.pir_program_selected'],
      tourChapterId: 'pir',
      tourStepIds: ['program-selector', 'step-nav'],
    },
    {
      id: 'school-pir-review',
      label: 'Reach the PIR review step',
      description: 'Complete the PIR sections and open the final review area.',
      route: '/pir',
      completeOn: ['author.pir_review_area_opened'],
      tourChapterId: 'pir',
      tourStepIds: ['review-submit'],
    },
  ],
  hints: [
    {
      id: 'author-autosave',
      pathname: '/aip',
      target: 'form-autosave',
      title: 'This form auto-saves while you work',
      description: 'You can safely pause after entering a first draft section. Save Draft is still available whenever you want a manual checkpoint.',
      requiredTaskId: 'school-open-form',
      pendingTaskId: 'school-save',
    },
  ],
  practiceTasks: [
    {
      id: 'practice-school-submit-aip',
      label: 'Practice: Submit an AIP',
      description: 'Walk through the AIP submission step on a mock program - no real data is affected.',
      practiceType: 'aip_submit',
      completeOn: ['practice.aip_submitted'],
    },
    {
      id: 'practice-school-file-pir',
      label: 'Practice: File a PIR',
      description: 'Try the quarterly PIR filing flow without submitting anything real.',
      practiceType: 'pir_submit',
      completeOn: ['practice.pir_submitted'],
    },
  ],
};
