<#
.SYNOPSIS
Deploys the AIP-PIR Docker Compose stack from a Windows PowerShell session.

.DESCRIPTION
For end-to-end deployment, prefer the master wizard:
  scripts\deploy-windows-wizard.ps1
This script is the workhorse it delegates to and can also be run standalone.

Creates or updates the root .env file, generates missing secrets, builds the
Docker images, starts the Compose services, and checks the backend health
endpoint. The defaults are tuned for direct testing through the assigned static
IP, but you can pass domain-based HTTPS URLs when DNS and TLS are ready.

.EXAMPLE
.\scripts\deploy-windows.ps1

.EXAMPLE
.\scripts\deploy-windows.ps1 `
  -EnableSsl `
  -Domain aip-pir.depedguihulngan.ph `
  -EnableBackup

.EXAMPLE
.\scripts\deploy-windows.ps1 -PrepareOnly
#>

[CmdletBinding()]
param(
  [string]$FrontendUrl = "http://222.127.76.11",
  [string]$ApiUrl = "http://222.127.76.11:3001",
  [int]$FrontendPort = 80,
  [string]$Domain = "aip-pir.depedguihulngan.ph",
  [string]$EnvFile = ".env",
  [switch]$EnableSsl,
  [switch]$EnableBackup,
  [switch]$SkipBuild,
  [switch]$SkipHealthCheck,
  [switch]$PrepareOnly,
  [switch]$ConfigureFirewall,
  [switch]$ExposeBackendPort
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-Path (Join-Path $scriptDir "..")
Set-Location $repoRoot

if ($EnableSsl) {
  if (-not $PSBoundParameters.ContainsKey("FrontendUrl")) {
    $FrontendUrl = "https://$Domain"
  }
  if (-not $PSBoundParameters.ContainsKey("ApiUrl")) {
    $ApiUrl = "https://$Domain"
  }
  if (-not $PSBoundParameters.ContainsKey("FrontendPort")) {
    $FrontendPort = 8080
  }
}

function Write-Step {
  param([string]$Message)
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

function Get-Origin {
  param([string]$Value)

  try {
    $uri = [Uri]$Value
  } catch {
    throw "Invalid URL: $Value"
  }

  if (-not $uri.IsAbsoluteUri -or ($uri.Scheme -ne "http" -and $uri.Scheme -ne "https")) {
    throw "URL must start with http:// or https://: $Value"
  }

  return "$($uri.Scheme)://$($uri.Authority)".TrimEnd("/")
}

function Get-UrlPort {
  param([string]$Value)

  $uri = [Uri]$Value
  if ($uri.Port -gt 0) {
    return $uri.Port
  }

  if ($uri.Scheme -eq "https") {
    return 443
  }

  return 80
}

function New-RandomText {
  param([int]$Length = 48)

  $chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789".ToCharArray()
  $bytes = New-Object byte[] $Length
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }

  $result = New-Object System.Text.StringBuilder
  foreach ($byte in $bytes) {
    [void]$result.Append($chars[$byte % $chars.Length])
  }

  return $result.ToString()
}

function New-HexSecret {
  param([int]$ByteLength = 32)

  $bytes = New-Object byte[] $ByteLength
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }

  return ([System.BitConverter]::ToString($bytes)).Replace("-", "").ToLowerInvariant()
}

function Read-EnvLines {
  param([string]$Path)

  $lines = New-Object "System.Collections.Generic.List[string]"
  if (Test-Path $Path) {
    foreach ($line in Get-Content -LiteralPath $Path) {
      $lines.Add($line)
    }
  } else {
    $lines.Add("# AIP-PIR production environment")
    $lines.Add("# Generated by scripts/deploy-windows.ps1")
    $lines.Add("")
  }

  return $lines
}

function Get-EnvEntry {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Key
  )

  $pattern = "^\s*$([Regex]::Escape($Key))=(.*)$"
  foreach ($line in $Lines) {
    if ($line -match $pattern) {
      return $Matches[1]
    }
  }

  return $null
}

function Test-EnvPlaceholder {
  param([AllowNull()][string]$Value)

  if ([string]::IsNullOrWhiteSpace($Value)) { return $true }
  $trimmed = $Value.Trim().Trim('"').Trim("'")
  return $trimmed.StartsWith("change-me") -or
         $trimmed.StartsWith("your-") -or
         ($trimmed.StartsWith("<") -and $trimmed.EndsWith(">"))
}

function Set-EnvEntry {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Key,
    [string]$Value,
    [bool]$Overwrite = $true
  )

  $pattern = "^\s*$([Regex]::Escape($Key))="
  for ($i = 0; $i -lt $Lines.Count; $i++) {
    if ($Lines[$i] -match $pattern) {
      $current = Get-EnvEntry -Lines $Lines -Key $Key
      if ($Overwrite -or (Test-EnvPlaceholder -Value $current)) {
        $Lines[$i] = "$Key=$Value"
      }
      return
    }
  }

  $Lines.Add("$Key=$Value")
}

function Set-SecretEntry {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Key,
    [string]$Value
  )

  Set-EnvEntry -Lines $Lines -Key $Key -Value $Value -Overwrite:$false
}

function Require-Command {
  param([string]$Name)

  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "$Name was not found. Install Docker and make sure '$Name' is available in PATH."
  }
}

function Invoke-Docker {
  param([string[]]$Arguments)

  & docker @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "docker $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
  }
}

function Add-FirewallPort {
  param(
    [string]$Name,
    [int]$Port
  )

  if (-not (Get-Command New-NetFirewallRule -ErrorAction SilentlyContinue)) {
    Write-Warning "New-NetFirewallRule is not available on this machine."
    return
  }

  $existing = Get-NetFirewallRule -DisplayName $Name -ErrorAction SilentlyContinue
  if ($existing) {
    Write-Host "Firewall rule already exists: $Name"
    return
  }

  New-NetFirewallRule `
    -DisplayName $Name `
    -Direction Inbound `
    -Protocol TCP `
    -LocalPort $Port `
    -Action Allow `
    -Profile Any | Out-Null

  Write-Host "Added firewall rule: $Name"
}

function Wait-ForHealth {
  param([string]$HealthUrl)

  for ($attempt = 1; $attempt -le 30; $attempt++) {
    try {
      $response = Invoke-WebRequest -Uri $HealthUrl -UseBasicParsing -TimeoutSec 5
      if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
        Write-Host "Backend health check passed: $HealthUrl" -ForegroundColor Green
        return
      }
    } catch {
      Start-Sleep -Seconds 3
    }
  }

  Write-Warning "Backend health check did not pass yet: $HealthUrl"
  Write-Warning "Check logs with: docker compose logs backend --tail=100"
}

$frontendOrigin = Get-Origin $FrontendUrl
$apiOrigin = Get-Origin $ApiUrl
$apiPort = Get-UrlPort $apiOrigin
$backendHostPort = if ($apiPort -eq 80 -or $apiPort -eq 443) { 3001 } else { $apiPort }
$backendBindAddress = if ($ExposeBackendPort) { "0.0.0.0" } else { "127.0.0.1" }
$frontendPortBinding = if ($EnableSsl) { "127.0.0.1:$FrontendPort" } else { [string]$FrontendPort }
$trustProxy = if ($apiOrigin.StartsWith("https://")) { "true" } else { "false" }
$trustedProxyCidrs = if ($EnableSsl) { "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16" } else { "" }

Write-Step "Preparing environment file"
$envPath = Join-Path $repoRoot $EnvFile
$envLines = Read-EnvLines -Path $envPath

Set-EnvEntry -Lines $envLines -Key "POSTGRES_USER" -Value "postgres" -Overwrite:$false
Set-SecretEntry -Lines $envLines -Key "POSTGRES_PASSWORD" -Value (New-RandomText 48)
Set-EnvEntry -Lines $envLines -Key "POSTGRES_DB" -Value "pir_system" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "POSTGRES_BIND_ADDRESS" -Value "127.0.0.1" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "POSTGRES_PORT" -Value "5432" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "BACKEND_BIND_ADDRESS" -Value $backendBindAddress
Set-EnvEntry -Lines $envLines -Key "BACKEND_PORT" -Value ([string]$backendHostPort)
Set-EnvEntry -Lines $envLines -Key "BACKUP_DB_USER" -Value "backup_reader" -Overwrite:$false
Set-SecretEntry -Lines $envLines -Key "BACKUP_DB_PASSWORD" -Value (New-RandomText 48)

Set-SecretEntry -Lines $envLines -Key "JWT_SECRET" -Value (New-HexSecret 32)
Set-SecretEntry -Lines $envLines -Key "EMAIL_CONFIG_SECRET" -Value (New-HexSecret 32)

Set-EnvEntry -Lines $envLines -Key "ALLOWED_ORIGIN" -Value $frontendOrigin
Set-EnvEntry -Lines $envLines -Key "VITE_API_URL" -Value $apiOrigin
Set-EnvEntry -Lines $envLines -Key "FRONTEND_PORT" -Value $frontendPortBinding
Set-EnvEntry -Lines $envLines -Key "NODE_ENV" -Value "production"
Set-EnvEntry -Lines $envLines -Key "APP_DOMAIN" -Value $Domain
Set-EnvEntry -Lines $envLines -Key "HTTP_BIND_ADDRESS" -Value "0.0.0.0" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "HTTPS_BIND_ADDRESS" -Value "0.0.0.0" -Overwrite:$false

Set-EnvEntry -Lines $envLines -Key "OAUTH_REDIRECT_BASE_URL" -Value $apiOrigin
Set-SecretEntry -Lines $envLines -Key "OAUTH_STATE_SECRET" -Value (New-HexSecret 32)
Set-EnvEntry -Lines $envLines -Key "GOOGLE_CLIENT_ID" -Value "" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "GOOGLE_CLIENT_SECRET" -Value "" -Overwrite:$false

Set-EnvEntry -Lines $envLines -Key "RECAPTCHA_SECRET_KEY" -Value "" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "VITE_RECAPTCHA_SITE_KEY" -Value "" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "RECAPTCHA_BYPASS_PRIVATE_IPS" -Value "false" -Overwrite:$false

Set-EnvEntry -Lines $envLines -Key "SEED_ADMIN_EMAIL" -Value "admin@qpir.local" -Overwrite:$false
Set-SecretEntry -Lines $envLines -Key "SEED_ADMIN_PASSWORD" -Value (New-RandomText 32)
Set-EnvEntry -Lines $envLines -Key "SEED_ADMIN_MUST_CHANGE_PASSWORD" -Value "true" -Overwrite:$false

Set-EnvEntry -Lines $envLines -Key "TRUST_PROXY" -Value $trustProxy
Set-EnvEntry -Lines $envLines -Key "TRUSTED_PROXY_CIDRS" -Value $trustedProxyCidrs -Overwrite:$EnableSsl

Set-SecretEntry -Lines $envLines -Key "BACKUP_ENCRYPTION_KEY" -Value (New-HexSecret 32)
Set-EnvEntry -Lines $envLines -Key "BACKUP_RETENTION_DAYS" -Value "14" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "BACKUP_CLOUD_ENABLED" -Value "false" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "BACKUP_RCLONE_REMOTE" -Value "my_remote" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "BACKUP_RCLONE_PATH" -Value "/AIP-PIR-Backups" -Overwrite:$false
Set-EnvEntry -Lines $envLines -Key "RCLONE_CONFIG_DIR" -Value "./.docker/rclone" -Overwrite:$false

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines([string]$envPath, [string[]]$envLines.ToArray(), $utf8NoBom)
Write-Host "Environment ready: $EnvFile"

Write-Step "Preparing runtime folders"
New-Item -ItemType Directory -Force -Path "backups\hourly", "backups\daily", "backups\triggers" | Out-Null
if ($EnableBackup) {
  New-Item -ItemType Directory -Force -Path ".docker\rclone" | Out-Null
}

if ($ConfigureFirewall) {
  Write-Step "Configuring Windows Firewall"
  if ($EnableSsl) {
    Add-FirewallPort -Name "AIP-PIR HTTP TCP 80" -Port 80
    Add-FirewallPort -Name "AIP-PIR HTTPS TCP 443" -Port 443
  } else {
    Add-FirewallPort -Name "AIP-PIR Frontend TCP $FrontendPort" -Port $FrontendPort
  }

  if ($ExposeBackendPort) {
    Add-FirewallPort -Name "AIP-PIR Backend TCP $backendHostPort" -Port $backendHostPort
  } else {
    Write-Warning "Backend port $backendHostPort was not opened. Use -ExposeBackendPort for direct-IP testing, or put the API behind HTTPS."
  }
}

if ($PrepareOnly) {
  Write-Step "Prepare-only mode complete"
  Write-Host "Review $EnvFile, then rerun this script without -PrepareOnly to start Docker."
  exit 0
}

Write-Step "Checking Docker"
Require-Command "docker"
Invoke-Docker -Arguments @("version")
Invoke-Docker -Arguments @("compose", "version")

Write-Step "Starting Docker Compose stack"
$composeArgs = @("compose", "--env-file", $EnvFile)
if ($EnableSsl) {
  $composeArgs += @("--profile", "ssl")
}
if ($EnableBackup) {
  $composeArgs += @("--profile", "backup")
}
$composeArgs += @("up", "-d")
if (-not $SkipBuild) {
  $composeArgs += "--build"
}

Invoke-Docker -Arguments $composeArgs
Invoke-Docker -Arguments @("compose", "--env-file", $EnvFile, "ps")

if (-not $SkipHealthCheck) {
  Write-Step "Checking backend health"
  Wait-ForHealth -HealthUrl "$apiOrigin/api/health"
}

Write-Step "Deployment complete"
Write-Host "Frontend: $frontendOrigin"
Write-Host "Backend:  $apiOrigin"
Write-Host ""
Write-Host "Useful commands:"
Write-Host "  docker compose --env-file $EnvFile ps"
if ($EnableSsl) {
  Write-Host "  docker compose --env-file $EnvFile --profile ssl logs caddy --tail=100"
}
Write-Host "  docker compose --env-file $EnvFile logs backend --tail=100"
Write-Host "  docker compose --env-file $EnvFile logs frontend --tail=100"
if ($EnableBackup) {
  Write-Host "  docker compose --env-file $EnvFile logs backup --tail=100"
}
