ALTER TABLE "AIP" DROP COLUMN IF EXISTS "observer_notes";
ALTER TABLE "PIR" DROP COLUMN IF EXISTS "observer_notes";
ALTER TABLE "PIR" DROP COLUMN IF EXISTS "remarks";
ALTER TABLE "PIRActivityReview" DROP COLUMN IF EXISTS "admin_notes";
