// Default FAQ content seeded into the database on first run.
// After the first seed, the database is the source of truth and admins
// edit FAQs through the admin console. This file is only consulted when
// the `faq_items` table is empty.

export interface FaqDefault {
  category: string;
  icon_key: string;
  question: string;
  answer: string;
}

export const DEFAULT_FAQS: FaqDefault[] = [
  // ── General ────────────────────────────────────────────────────────────
  { category: "General", icon_key: "HelpCircle", question: "What is the AIP-PIR Portal?", answer: "The AIP-PIR Portal is the Schools Division of Guihulngan City's digital system for managing Annual Implementation Plans and Program Implementation Reviews in one role-aware workflow." },
  { category: "General", icon_key: "HelpCircle", question: "What does AIP stand for and what is it for?", answer: "AIP stands for Annual Implementation Plan. It is the planning baseline for the fiscal year and identifies target outcomes, projects, activities, timelines, persons involved, expected outputs, and budget sources." },
  { category: "General", icon_key: "HelpCircle", question: "What does PIR stand for and what is it for?", answer: "PIR stands for Program Implementation Review. It is the monitoring record that compares actual accomplishments and budget utilization against the AIP baseline, including facilitating and hindering factors." },
  { category: "General", icon_key: "HelpCircle", question: "Who can use the portal?", answer: "The Beta Build supports School Users, Division Personnel, CES reviewers (CES-SGOD, CES-ASDS, CES-CID), Admin users, Observers with read-only access, and Pending accounts awaiting administrator assignment. Your role controls which schools, programs, and review queues you can access." },
  { category: "General", icon_key: "HelpCircle", question: "What does Apir mean in this system?", answer: "Apir is Filipino for high five. The name AIP-PIR links planning and review as the two hands that meet to complete the program implementation cycle." },
  { category: "General", icon_key: "HelpCircle", question: "Which DepEd office runs this system?", answer: "The portal is operated by the Department of Education, Schools Division of Guihulngan City. Issues, account requests, and policy questions should be directed to the SDO." },
  { category: "General", icon_key: "HelpCircle", question: "Is this a final release?", answer: "No. The portal is currently labeled Beta 3 (v1.2.0-beta). Workflows, statuses, and reports may continue to evolve based on user feedback before a stable release." },

  // ── Accounts & Sign-In ────────────────────────────────────────────────
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "How do I sign in to the portal?", answer: "The portal supports password sign-in, magic-link sign-in via email, and Google OAuth sign-in when configured for the deployment. Use whichever method has been provisioned for your account." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "Can I sign in with Google?", answer: "Yes, when OAuth is configured for the deployment. Use the Google DepEd sign-in button on the login page; the backend verifies the DepEd account before starting a portal session." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "What is a magic link?", answer: "A magic link is a one-time sign-in URL sent to your email. Clicking it verifies your identity and starts a session without a password. Magic links expire after a short window and can only be used once." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "I forgot my password. How do I reset it?", answer: "Contact the SDO IT department or your administrator. Self-service password reset is not currently available; an administrator can issue a new password or arrange a magic-link sign-in." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "Why is my account stuck in Pending status?", answer: "New accounts, including OAuth sign-ups, are created in Pending state with restricted access. An administrator must assign your role (School, Division Personnel, CES, Observer, or Admin) before you can use role-specific features." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "Why does the portal mention cookies after login?", answer: "The portal stores the session in an HttpOnly cookie that the browser sends with each request. If login succeeds but you return to the login page, check whether your browser blocks cookies for the portal domain or whether the HTTPS or tunnel origin is misconfigured." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "Can multiple people share one school account?", answer: "The Beta Build enforces one active School-role account per school so AIP and PIR ownership stays clear. Contact the SDO administrator if the assigned account needs to be changed." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "How long does my session stay signed in?", answer: "Each session has a server-side expiry. Closing the browser tab does not necessarily sign you out, but the session is revoked when you click Logout, when an administrator revokes it, or when it reaches its expiry." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "What happens when I log out?", answer: "Logout revokes your server-side session, clears the authentication cookie, and removes locally cached drafts and session metadata in the browser. You will need to sign in again to resume work." },
  { category: "Accounts & Sign-In", icon_key: "HelpCircle", question: "Can I be signed in on multiple devices?", answer: "Yes. Each sign-in creates its own session row. Administrators can review and revoke individual sessions if a device is lost or compromised." },

  // ── AIP Submissions ───────────────────────────────────────────────────
  { category: "AIP Submissions", icon_key: "BookOpen", question: "How do I create an AIP?", answer: "Open the AIP form for your assigned program and fiscal year, fill in activities under the Planning, Implementation, and Monitoring and Evaluation phases, then save a draft or submit. School users submit on behalf of their school; Division Personnel can submit division-level AIPs." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "What are the AIP activity phases?", answer: "Each activity is grouped under one of three phases: Planning, Implementation, or Monitoring and Evaluation. The phase reflects when in the program lifecycle the activity occurs and is used to organize the AIP and the resulting PIR review rows." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "Can I have more than one AIP for the same program and year?", answer: "No. The system enforces one school AIP per school, program, and fiscal year. Division-level AIPs follow a similar rule per division user. If you need to revise an approved AIP, contact your administrator." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "Why can't I submit my school AIP?", answer: "School AIPs require focal-person assignments on the selected program before they can enter the recommendation workflow. If the program has no assigned focal persons, ask your administrator to set them up first." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "Why can't I see certain programs?", answer: "Programs are filtered by school level, explicit restrictions, and Division Personnel program assignments. Restricted programs such as ALS school-based options only appear for authorized schools." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "What happens after I submit an AIP?", answer: "A school AIP enters For Recommendation and appears in the queue of the assigned focal person. After focal recommendation it moves to For CES Review for the appropriate functional division. Division-level AIPs follow a simpler path managed by Division Personnel." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "What does it mean when my AIP is Returned?", answer: "A focal person or CES reviewer has sent the AIP back for correction with remarks. Open the same record, address the remarks, and resubmit. The record returns to the appropriate review queue." },
  { category: "AIP Submissions", icon_key: "BookOpen", question: "Can I delete an AIP after submitting it?", answer: "Submitted AIPs cannot be deleted from the user interface so the audit trail stays intact. Draft AIPs can be discarded. If an approved AIP needs to be retracted, contact your administrator." },

  // ── PIR Submissions ───────────────────────────────────────────────────
  { category: "PIR Submissions", icon_key: "BookOpen", question: "Can I submit a PIR without an approved AIP?", answer: "No. A PIR can only be created after an AIP has been submitted for the same school or Division Personnel account, program, and fiscal year." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "Why are my AIP activities already filled in on the PIR form?", answer: "The PIR form loads the linked AIP activities automatically so your accomplishments stay traceable to the original plan. You only need to fill in the physical and financial accomplishment details." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "Why are some activities missing from my PIR?", answer: "The PIR form uses timeline-aware filtering. It only shows activities whose implementation months overlap with the quarter you are currently reviewing." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "Can I submit multiple PIRs for one AIP?", answer: "Yes. You can submit one PIR per quarter for each AIP in a fiscal year (Q1, Q2, Q3, and Q4). The system enforces one PIR per AIP and reporting period." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "What is the difference between physical and financial accomplishments?", answer: "Physical accomplishments capture what was actually done, such as numbers of beneficiaries reached or outputs produced. Financial accomplishments capture the corresponding amounts utilized against the planned budget." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "What are facilitating and hindering factors?", answer: "Factors describe conditions that helped or hindered implementation. The PIR groups them by type — institutional, technical, infrastructure, learning resources, environmental, and other — and lets you attach recommendations alongside them." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "What is a MOV?", answer: "MOV stands for Means of Verification. It is the document, file, or record that substantiates an accomplishment, such as attendance sheets, photos, or output files referenced in the PIR." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "What happens if I miss a PIR deadline?", answer: "Deadlines and trimester windows are configured by the administrator. Submission outside the configured window may be blocked or marked late depending on configuration. Contact your administrator if you missed a deadline." },
  { category: "PIR Submissions", icon_key: "BookOpen", question: "Why does my PIR enter For Admin Review instead of For CES Review?", answer: "If you submit a PIR while signed in with a CES role, the record routes to For Admin Review because a CES user cannot review their own submission. The administrator handles the record from the consolidation view." },

  // ── Review & Workflow Statuses ───────────────────────────────────────
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does Draft mean?", answer: "Draft is a saved-but-not-submitted record that only you (the owner) can see and edit. Drafts persist on the server so you can resume work from another device." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does For Recommendation mean?", answer: "A school-owned AIP or PIR is in the focal-person queue for the program. The assigned focal person can recommend it (sending it to CES Review) or return it for correction." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does For CES Review mean?", answer: "An AIP or PIR with this status is in the CES queue for the program's functional division. CES-SGOD reviews SGOD programs, CES-ASDS reviews OSDS programs, and CES-CID reviews CID programs and programs without a declared division." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does Under Review mean?", answer: "A CES reviewer has explicitly started reviewing the PIR. This status indicates active review and helps avoid two reviewers acting on the same record at once." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does For Admin Review mean?", answer: "A PIR submitted by a CES-role user enters this holding state because CES users cannot review their own work. Administrators see the record in the consolidation view." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does Approved mean?", answer: "The reviewer has accepted the record. Approved records become read-only. For AIPs, approval is what unlocks the corresponding PIR." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What does Returned mean?", answer: "A reviewer sent the record back for correction. The submitter receives a notification with the reviewer's remarks and can edit and resubmit." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "What happens when a PIR is returned?", answer: "You receive an in-app notification with the reviewer remarks. Open the same program and quarter, make the correction, then submit again. Returned PIRs go back to the appropriate recommendation or CES review queue." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "Can I edit a PIR while it is being reviewed?", answer: "No. PIRs in active review statuses are locked until a reviewer returns them. Draft and Returned PIRs can be edited; approved or terminal submissions stay locked." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "Who is a Focal Person?", answer: "A Focal Person is a Division Personnel user assigned to one or more programs. They review school submissions before CES review and can either recommend or return them with remarks." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "Which CES role reviews which programs?", answer: "CES-SGOD reviews SGOD programs, CES-ASDS reviews OSDS programs, and CES-CID reviews CID programs and any programs that do not yet have a declared functional division." },
  { category: "Review & Workflow Statuses", icon_key: "AlertCircle", question: "Can Admin approve school AIPs or PIRs directly?", answer: "Admin users have oversight tools but do not act as focal or CES reviewers for the normal school review chain. AIP and PIR approvals go through the configured focal and CES roles." },

  // ── Drafts, Editing & Documents ───────────────────────────────────────
  { category: "Drafts, Editing & Documents", icon_key: "BookOpen", question: "Can I save my progress and continue later?", answer: "Yes. Save Draft stores your form state server-side so you can continue later from another device. PIR drafts are tied to the selected program, year, and quarter." },
  { category: "Drafts, Editing & Documents", icon_key: "BookOpen", question: "How long does my draft stay saved?", answer: "Drafts remain available until you submit the record, discard the draft, or your administrator deletes related data. They are not auto-expired." },
  { category: "Drafts, Editing & Documents", icon_key: "BookOpen", question: "My draft did not restore. What should I check?", answer: "Make sure you selected the same program, fiscal year, and quarter you were using when you saved the draft. If it still does not appear, contact the SDO IT department." },
  { category: "Drafts, Editing & Documents", icon_key: "BookOpen", question: "Can two people edit the same draft at the same time?", answer: "Drafts are owned by a single account. The system protects against duplicate submissions for the same school, program, and period, but coordination among co-authors should happen outside the system." },
  { category: "Drafts, Editing & Documents", icon_key: "BookOpen", question: "Can I download or print my AIP or PIR?", answer: "Yes. Each submitted record has a print-ready document view generated directly from the stored data. Use your browser's print dialog or print-to-PDF to save a copy." },
  { category: "Drafts, Editing & Documents", icon_key: "BookOpen", question: "Why does my downloaded document look different in another browser?", answer: "Generated documents rely on browser rendering and print settings, which vary between browsers and operating systems. For consistent output, prefer the same browser and use the standard A4 print preset." },

  // ── Notifications & Announcements ─────────────────────────────────────
  { category: "Notifications & Announcements", icon_key: "BookOpen", question: "Where do I see notifications?", answer: "The bell icon in the dashboard header opens your notification list. Unread notifications are highlighted and clicking a notification jumps to the related record when available." },
  { category: "Notifications & Announcements", icon_key: "BookOpen", question: "Are notifications real-time?", answer: "Yes. The portal keeps an event stream open so workflow updates appear without manually refreshing. If the stream is blocked, the notification list still loads from the standard API on each navigation." },
  { category: "Notifications & Announcements", icon_key: "BookOpen", question: "How do notification links work?", answer: "In-app notifications include entity metadata when available. Clicking supported notifications opens the related AIP, PIR, or announcement instead of leaving you to search for it manually." },
  { category: "Notifications & Announcements", icon_key: "BookOpen", question: "What should I do if real-time notifications stop updating?", answer: "Refresh the page first. If a tunnel proxy or CORS issue blocks the live event stream, the portal still loads existing notifications from the normal notifications API." },
  { category: "Notifications & Announcements", icon_key: "BookOpen", question: "What is an announcement?", answer: "Announcements are messages posted by administrators to inform users about deadlines, system changes, or operational notices. They can target all users or specific roles." },

  // ── Programs, Schools & Deadlines ─────────────────────────────────────
  { category: "Programs, Schools & Deadlines", icon_key: "BookOpen", question: "What is a cluster?", answer: "A cluster groups related schools for organizational reporting. Schools belong to one cluster, and reports can be aggregated by cluster in addition to school and division levels." },
  { category: "Programs, Schools & Deadlines", icon_key: "BookOpen", question: "Where do school and cluster logos come from?", answer: "The portal uses an uploaded school logo first, then the uploaded cluster logo, then the bundled default cluster logo when no upload exists." },
  { category: "Programs, Schools & Deadlines", icon_key: "BookOpen", question: "What is a trimester deadline?", answer: "Trimester deadlines define submission windows for specific reporting periods. The administrator configures the open and close dates and optional grace periods that the system enforces." },
  { category: "Programs, Schools & Deadlines", icon_key: "BookOpen", question: "Why is a program tagged with a functional division?", answer: "Each program carries a division attribute (SGOD, OSDS, CID, or unassigned). The division determines which CES role reviews the program and how it appears in division-level reports." },
  { category: "Programs, Schools & Deadlines", icon_key: "BookOpen", question: "What is a program restriction?", answer: "Some programs are restricted to certain schools, such as ALS school-based options for specific school types. Restrictions hide the program from schools that should not submit it and prevent accidental encoding." },

  // ── Admin & Configuration ─────────────────────────────────────────────
  { category: "Admin & Configuration", icon_key: "HelpCircle", question: "What can Admin manage?", answer: "Admin users can manage overview metrics, users, schools, clusters, programs, deadlines, submissions, PIR review, reports, backups, settings, announcements, audit logs, school logos, and cluster logos." },
  { category: "Admin & Configuration", icon_key: "HelpCircle", question: "How do I add or remove a user?", answer: "From the Users page in the admin console, an administrator can create accounts, change roles, deactivate accounts, or anonymize accounts that should no longer be associated with personal data." },
  { category: "Admin & Configuration", icon_key: "HelpCircle", question: "How do reports work?", answer: "Admin users can generate compliance, monitoring, budget, workload, accomplishment, factor, AIP funnel, and cluster summary reports. Reports can typically be exported as CSV or XLSX where supported." },
  { category: "Admin & Configuration", icon_key: "HelpCircle", question: "How do backups work?", answer: "Backups are triggered or scheduled through the admin console. The status view shows recent backup runs. The portal does not run database backups itself; it integrates with the configured backup service." },
  { category: "Admin & Configuration", icon_key: "HelpCircle", question: "Can Admin restore deleted data?", answer: "Soft-deleted records keep a deletion timestamp rather than removing rows, which preserves history. Restoring data requires administrator action and may depend on the configured backup retention policy." },
  { category: "Admin & Configuration", icon_key: "HelpCircle", question: "What is an audit log?", answer: "The audit log captures administrative actions and selected workflow events for accountability. Admin users can review the log to investigate changes." },

  // ── Privacy & Data Handling ───────────────────────────────────────────
  { category: "Privacy & Data Handling", icon_key: "HelpCircle", question: "What personal data does the portal store?", answer: "The portal stores account profile information (name, email, role, school assignment), authentication metadata, sessions, submission ownership, review remarks, and activity logs needed to operate the workflow." },
  { category: "Privacy & Data Handling", icon_key: "HelpCircle", question: "Can I export my personal data?", answer: "Yes. Administrators can produce a personal-data export for a user account in support of Data Privacy Act obligations. Contact the administrator to request an export." },
  { category: "Privacy & Data Handling", icon_key: "HelpCircle", question: "Can my account be anonymized or deleted?", answer: "Accounts can be soft-deleted or anonymized by an administrator. Anonymization removes personal identifiers while retaining workflow history so review records remain consistent." },
  { category: "Privacy & Data Handling", icon_key: "HelpCircle", question: "Are my submissions kept forever?", answer: "Submissions are retained as part of the official AIP and PIR record. They are not auto-purged. Retention beyond the operating period follows DepEd policy and the administrator's configuration." },
  { category: "Privacy & Data Handling", icon_key: "HelpCircle", question: "How are sessions and cookies protected?", answer: "Sessions are stored in HttpOnly cookies that JavaScript cannot read, paired with a server-side session row that can be revoked. This reduces exposure to client-side token theft." },

  // ── Technical Support ─────────────────────────────────────────────────
  { category: "Technical Support", icon_key: "AlertCircle", question: "I see a duplicate submission error. What does it mean?", answer: "The system prevents two submissions for the same school, program, and reporting period from being created at once. If you see this error, refresh the list — your previous submission likely already saved successfully." },
  { category: "Technical Support", icon_key: "AlertCircle", question: "The page is not loading. What should I do?", answer: "First, refresh the page. If the issue persists, check your internet connection, try signing out and back in, and clear your browser's site data for the portal. If it still fails, contact the SDO IT department with the error message and approximate time." },
  { category: "Technical Support", icon_key: "AlertCircle", question: "I see a CORS or cookie warning. What is happening?", answer: "This usually indicates that the portal is being accessed through an unexpected origin or that browser cookies are blocked. Confirm the URL matches the official portal address and that cookies are enabled for that domain." },
  { category: "Technical Support", icon_key: "AlertCircle", question: "Why am I being signed out unexpectedly?", answer: "Possible causes include session expiry, the session being revoked by an administrator, sign-in from another device that invalidated this one, or a backend restart. Sign in again and contact support if it keeps happening." },
  { category: "Technical Support", icon_key: "AlertCircle", question: "How do I report a bug or request a feature?", answer: "Contact the SDO IT department or your administrator with a description of the issue, the steps to reproduce it, and approximate timestamps. Screenshots help. Feature requests are tracked alongside the Beta release roadmap." },
  { category: "Technical Support", icon_key: "AlertCircle", question: "Where can I find user documentation?", answer: "The Help Center hosts this FAQ plus role-aware onboarding inside the dashboard. Detailed system documentation is also maintained as a technical reference and is available from the administrator on request." },
];

export const SUPPORTED_FAQ_ICONS = [
  "HelpCircle",
  "BookOpen",
  "AlertCircle",
  "Shield",
  "Gear",
  "ChatCircle",
] as const;

export type FaqIconKey = typeof SUPPORTED_FAQ_ICONS[number];

export function isSupportedIcon(key: unknown): key is FaqIconKey {
  return typeof key === "string" &&
    (SUPPORTED_FAQ_ICONS as readonly string[]).includes(key);
}
